### ISSUE TITLE
gfwlist无法更新

### ISSUE THREAD

**Issue by kenneth104** [fanck0605/openwrt-ci#14]
我的另一台openwrt可以更新
r2s也可以出国

但r2s无法更新gfwlist

<img src="https://tinypng.com/web/output/qzcv9xf8meq91mrnvcy6y16bbgynujd1/%E6%88%AA%E5%9B%BE%E5%BD%95%E5%B1%8F_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20210128163930.png">

**Comment by kenneth104** [comment]
刷的是squashfs
完成后运行firstboot -y && reboot now

**Comment by woyin** [comment]
我也具有相同问题，不论是gfwlist还是国内IP或者网飞IP，均不能更新。

**Comment by fanck0605** [comment]
可能是因为新版的 wget 不在 PATH 下提供 wget-ssl，执行一下
```shell
ln -s /usr/bin/wget /usr/bin/wget-ssl
```
试一下

**Comment by woyin** [comment]
> 可能是因为新版的 wget 不在 PATH 下提供 wget-ssl，执行一下
> 
> ```shell
> ln -s /usr/bin/wget /usr/bin/wget-ssl
> ```
> 
> 试一下

回去试试，谢谢大佬~

**Comment by fanck0605** [comment]
新版已经都正常了
