### ISSUE TITLE
新买的闪迪内存卡，刷了以后开机无法获取IP，进不去后台

### ISSUE THREAD

**Issue by gimgoo** [fanck0605/openwrt-ci#16]
如题，新买的闪迪内存卡，刷了以后开机无法获取IP。一直都是16开头的那个内网地址，两个口换着插也一样。
但是系统的灯是正常的，风扇都是转的。

**Comment by Peatercat** [comment]
应该是刷错固件了，我也遇到过，刷对固件就正常了……

William Zhang <notifications@github.com> 于 2021年2月6日周六 00:51写道：

**Comment by fanck0605** [comment]
没遇到同样的问题。
