### ISSUE TITLE
使用ssrp和openclash出错

### ISSUE THREAD

**Issue by ghost** [fanck0605/openwrt-ci#17]
点击ssrp或openclash出错
日志：
/usr/lib/lua/luci/dispatcher.lua:1347: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1347: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1024: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:1000: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

**Comment by ghost** [comment]
重新刷固件后解决问题，尚未知晓错误原因

**Comment by ghost** [comment]
复现了一下错误 是在卸载luci-app-unblockneteasemusic并且勾选automatically remove unused dependencise时会引发这个错误
版本release 20210221

**Comment by fanck0605** [comment]
opkg 依赖判断的时候出问题了，把不该卸载的 unzip luci-compat 都卸了。
这是 opkg 的 bug 吧，这个我解决不了。

你可以 clone 我的项目，删除 config.seed 里的 luci-app-unblockneteasemusic 一整行，github actions 就会编译一个不带 unblockneteasemusic 的固件

```
Removing package luci-app-unblockneteasemusic from root...
busybox was autoinstalled and is now orphaned, removing.
Refusing to remove essential package busybox.
	Removing an essential package may lead to an unusable system, but if
	you enjoy that kind of pain, you can force opkg to proceed against
	its will with the option: --force-removal-of-essential-packages
unzip was autoinstalled and is now orphaned, removing.
Removing package unzip from root...
luci-compat was autoinstalled and is now orphaned, removing.
Removing package luci-compat from root...
No packages removed.
```

**Comment by ghost** [comment]
我在使用 release 20210116 的时候也卸载了 luci-app-unblockneteasemusic 并且勾选了 automatically remove unused dependencise，当时貌似并未出现任何问题，该问题是 20210221 版本才遇到的。

如果您有精力的话可以查看一下该问题是否是 20210221 版本才出现的，我手上的设备不太方便做测试

**Comment by fanck0605** [comment]
这是 luci-app-unblockneteasemusic 的问题，现在已经不内置该应用
