### ISSUE TITLE
不定时断网

### ISSUE THREAD

**Issue by abluejay-piyo** [fanck0605/openwrt-ci#21]
突然断网，拔掉部分网线才能恢复正常，插入后又断。
系统日志：
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.905742] ------------[ cut here ]------------
> Sun Apr 18 12:14:29 2021 kern.info kernel: [ 1064.906216] NETDEV WATCHDOG: eth1 (r8152): transmit queue 0 timed out
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.906912] WARNING: CPU: 2 PID: 0 at net/sched/sch_generic.c:448 dev_watchdog+0x2f4/0x300
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.907645] Modules linked in: pppoe ppp_async pppox ppp_generic ipt_REJECT xt_time xt_tcpudp xt_state xt_socket xt_quota xt_pkttype xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_addrtype xt_TPROXY xt_TCPMSS xt_REDIRECT xt_MASQUERADE xt_LOG xt_FLOWOFFLOAD usbnet tcp_bbr slhc r8152 nf_tproxy_ipv6 nf_tproxy_ipv4 nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_conntrack_rtcache nf_conntrack_netlink iptable_nat iptable_mangle iptable_filter ip_tables crc_ccitt xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6table_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip6t_NPT nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.907903]  x_tables nf_reject_ipv6 tun vfat fat nls_utf8 nls_cp437 crypto_user algif_skcipher algif_rng algif_hash algif_aead af_alg gpio_button_hotplug antfs
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.916757] CPU: 2 PID: 0 Comm: swapper/2 Not tainted 5.4.99 #0
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.917285] Hardware name: FriendlyElec NanoPi R2S (DT)
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.917758] pstate: 20000005 (nzCv daif -PAN -UAO)
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.918194] pc : dev_watchdog+0x2f4/0x300
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.918559] lr : dev_watchdog+0x2f4/0x300
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.918920] sp : ffff800010013da0
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.919219] x29: ffff800010013da0 x28: ffff00003c467e80
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.919698] x27: 0000000000000004 x26: 0000000000000140
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.920177] x25: 00000000ffffffff x24: 0000000000000002
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.920657] x23: ffff00003c7dd45c x22: ffff00003c7dd000
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.921138] x21: ffff00003c7dd478 x20: ffff800010b96000
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.921617] x19: 0000000000000000 x18: 0000000000000000
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.922097] x17: 0000000000000000 x16: 0000000000000000
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.922577] x15: 0000000000000000 x14: ffff800010c1f092
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.923053] x13: 0000000000000000 x12: ffff800010c1e000
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.923533] x11: ffff800010baa000 x10: 0000000000000010
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.924009] x9 : 0000000000000000 x8 : 656d697420302065
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.924489] x7 : 756575712074696d x6 : ffff00003f59e710
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.924970] x5 : ffff00003f59e710 x4 : 0000000000000004
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.925449] x3 : 0000000000000000 x2 : 0000000000000004
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.925928] x1 : ffff00003d8d9780 x0 : 0000000000000039
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.926411] Call trace:
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.926647]  dev_watchdog+0x2f4/0x300
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.926987]  call_timer_fn.isra.35+0x20/0x78
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.927377]  run_timer_softirq+0x378/0x388
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.927752]  __do_softirq+0x124/0x260
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.928086]  irq_exit+0xb8/0xc8
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.928381]  handle_IPI+0x114/0x1a8
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.928698]  gic_handle_irq+0x9c/0xa8
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.929033]  el1_irq+0xb8/0x180
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.929329]  cpuidle_enter_state+0x84/0x358
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.929710]  cpuidle_enter+0x34/0x48
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.930043]  call_cpuidle+0x1c/0x40
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.930363]  do_idle+0x1c0/0x218
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.930665]  cpu_startup_entry+0x24/0x78
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.931026]  secondary_start_kernel+0x16c/0x180
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.931435] ---[ end trace f8a723d4b12a59ca ]---
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.931960] r8152 4-1:1.0 eth1: Tx timeout
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.935190] r8152 4-1:1.0 eth1: Tx status -2
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.935661] r8152 4-1:1.0 eth1: Tx status -2
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.936110] r8152 4-1:1.0 eth1: Tx status -2
> Sun Apr 18 12:14:29 2021 kern.warn kernel: [ 1064.936563] r8152 4-1:1.0 eth1: Tx status -2
> Sun Apr 18 12:14:31 2021 kern.info kernel: [ 1067.069315] usb 4-1: reset SuperSpeed Gen 1 USB device number 2 using xhci-hcd
> Sun Apr 18 12:14:31 2021 kern.err kernel: [ 1067.101549] r8152 4-1:1.0 eth1: Invalid ether addr 00:00:00:00:00:00
> Sun Apr 18 12:14:31 2021 kern.info kernel: [ 1067.102180] r8152 4-1:1.0 eth1: Random ether addr 62:9a:7f:1d:ff:25
> Sun Apr 18 12:14:31 2021 kern.notice kernel: [ 1067.106035] r8152 4-1:1.0 eth1: Promiscuous mode enabled

**Comment by abluejay-piyo** [comment]
内核日志：
[   20.796490] rk_gmac-dwmac ff540000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
[   20.797314] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 1064.905742] ------------[ cut here ]------------
[ 1064.906216] NETDEV WATCHDOG: eth1 (r8152): transmit queue 0 timed out
[ 1064.906912] WARNING: CPU: 2 PID: 0 at net/sched/sch_generic.c:448 dev_watchdog+0x2f4/0x300
[ 1064.907645] Modules linked in: pppoe ppp_async pppox ppp_generic ipt_REJECT xt_time xt_tcpudp xt_state xt_socket xt_quota xt_pkttype xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_addrtype xt_TPROXY xt_TCPMSS xt_REDIRECT xt_MASQUERADE xt_LOG xt_FLOWOFFLOAD usbnet tcp_bbr slhc r8152 nf_tproxy_ipv6 nf_tproxy_ipv4 nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_conntrack_rtcache nf_conntrack_netlink iptable_nat iptable_mangle iptable_filter ip_tables crc_ccitt xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6table_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip6t_NPT nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT
[ 1064.907903]  x_tables nf_reject_ipv6 tun vfat fat nls_utf8 nls_cp437 crypto_user algif_skcipher algif_rng algif_hash algif_aead af_alg gpio_button_hotplug antfs
[ 1064.916757] CPU: 2 PID: 0 Comm: swapper/2 Not tainted 5.4.99 #0
[ 1064.917285] Hardware name: FriendlyElec NanoPi R2S (DT)
[ 1064.917758] pstate: 20000005 (nzCv daif -PAN -UAO)
[ 1064.918194] pc : dev_watchdog+0x2f4/0x300
[ 1064.918559] lr : dev_watchdog+0x2f4/0x300
[ 1064.918920] sp : ffff800010013da0
[ 1064.919219] x29: ffff800010013da0 x28: ffff00003c467e80 
[ 1064.919698] x27: 0000000000000004 x26: 0000000000000140 
[ 1064.920177] x25: 00000000ffffffff x24: 0000000000000002 
[ 1064.920657] x23: ffff00003c7dd45c x22: ffff00003c7dd000 
[ 1064.921138] x21: ffff00003c7dd478 x20: ffff800010b96000 
[ 1064.921617] x19: 0000000000000000 x18: 0000000000000000 
[ 1064.922097] x17: 0000000000000000 x16: 0000000000000000 
[ 1064.922577] x15: 0000000000000000 x14: ffff800010c1f092 
[ 1064.923053] x13: 0000000000000000 x12: ffff800010c1e000 
[ 1064.923533] x11: ffff800010baa000 x10: 0000000000000010 
[ 1064.924009] x9 : 0000000000000000 x8 : 656d697420302065 
[ 1064.924489] x7 : 756575712074696d x6 : ffff00003f59e710 
[ 1064.924970] x5 : ffff00003f59e710 x4 : 0000000000000004 
[ 1064.925449] x3 : 0000000000000000 x2 : 0000000000000004 
[ 1064.925928] x1 : ffff00003d8d9780 x0 : 0000000000000039 
[ 1064.926411] Call trace:
[ 1064.926647]  dev_watchdog+0x2f4/0x300
[ 1064.926987]  call_timer_fn.isra.35+0x20/0x78
[ 1064.927377]  run_timer_softirq+0x378/0x388
[ 1064.927752]  __do_softirq+0x124/0x260
[ 1064.928086]  irq_exit+0xb8/0xc8
[ 1064.928381]  handle_IPI+0x114/0x1a8
[ 1064.928698]  gic_handle_irq+0x9c/0xa8
[ 1064.929033]  el1_irq+0xb8/0x180
[ 1064.929329]  cpuidle_enter_state+0x84/0x358
[ 1064.929710]  cpuidle_enter+0x34/0x48
[ 1064.930043]  call_cpuidle+0x1c/0x40
[ 1064.930363]  do_idle+0x1c0/0x218
[ 1064.930665]  cpu_startup_entry+0x24/0x78
[ 1064.931026]  secondary_start_kernel+0x16c/0x180
[ 1064.931435] ---[ end trace f8a723d4b12a59ca ]---
[ 1064.931960] r8152 4-1:1.0 eth1: Tx timeout
[ 1064.935190] r8152 4-1:1.0 eth1: Tx status -2
[ 1064.935661] r8152 4-1:1.0 eth1: Tx status -2
[ 1064.936110] r8152 4-1:1.0 eth1: Tx status -2
[ 1064.936563] r8152 4-1:1.0 eth1: Tx status -2
[ 1067.069315] usb 4-1: reset SuperSpeed Gen 1 USB device number 2 using xhci-hcd
[ 1067.101549] r8152 4-1:1.0 eth1: Invalid ether addr 00:00:00:00:00:00
[ 1067.102180] r8152 4-1:1.0 eth1: Random ether addr 62:9a:7f:1d:ff:25
[ 1067.106035] r8152 4-1:1.0 eth1: Promiscuous mode enabled

**Comment by fanck0605** [comment]
用了几年了，没遇到过。现在 OpenWrt 官方代码已经很稳了。
