### ISSUE TITLE
关于默认lan wan口互换

### ISSUE THREAD

**Issue by jackiegk** [fanck0605/openwrt-ci#3]
请问下 为什么要这么设置呢
如果我要改成正常 要修改哪个设置呢

**Comment by fanck0605** [comment]
@jackiegk
wan 口是原生的，lan 口是通过 usb3 转接的，互换后可能会更稳定。
删除 patches 下的 swap wan and lan 补丁即可。
其他不喜欢的修改，也是删对应补丁即可。

**Comment by jackiegk** [comment]
懂了 谢谢解答
