### ISSUE TITLE
是否支持nanopi neo3

### ISSUE THREAD

**Issue by r0ckstill** [fanck0605/openwrt-ci#8]
neo3和r2s使用同样的cpu

**Comment by fanck0605** [comment]
不支持的嗷，我只是代码的搬运工，不知道如何适配。

**Comment by r0ckstill** [comment]
> 不支持的嗷，我只是代码的搬运工，不知道如何适配。

官方的friendlywrt两者代码一样的，不知道第三方的编译出来能不能直接用

**Comment by hilobekerfulaisien** [comment]
能不能跟原版开发者说下，请直接把这个放到openwrt.org的设备列表里，不需要大家跑来某人仓库下载。也跟着一大批其他openwrt的维护者一起更新。
