### ISSUE TITLE
能否添加PWM FAN功能

### ISSUE THREAD

**Issue by CWZ7605** [fanck0605/openwrt-ci#9]
大佬可否在openwrt中添加PWM FAN的功能。自从从friendlywrt转过来，我的风扇就一直全速呼呼，很怕它英年早逝。

**Comment by suyiping** [comment]
> 大佬可否在openwrt中添加PWM FAN的功能。自从从friendlywrt转过来，我的风扇就一直全速呼呼，很怕它英年早逝。

可以自己添加friendlywrt的fan pwm脚本实现控制

**Comment by fanck0605** [comment]
主要我没有风扇，加了也没法调呀

**Comment by CWZ7605** [comment]
> 
> 
> 主要我没有风扇，加了也没法调呀

可给大佬免费提供一只风扇

**Comment by suyiping** [comment]
修改方法(所需文件请通过参考链接2下载)：
	1. 
通过OpenWrt TTYD终端上传friendlywrt/target/linux/rockchip-rk3328/base-files/usr/bin/start-rk3328-pwm-fan.sh到系统/usr/bin/目录下并通过chmod 777 start-rk3328-pwm-fan.sh修改脚本权限。
	2. 
通过OpenWrt TTYD终端上传friendlywrt/target/linux/rockchip-rk3328/base-files/etc/init.d/fa-rk3328-pwmfan到系统/etc/init.d/目录下，并通过chmod 777 fa-rk3328-pwmfan修改脚本权限。
	3. 
通过命令ln -s /etc/init.d/fa-rk3328-pwmfan /etc/rc.d/S96fa-rk3328-pwmfan创建一个启动脚本的软链接到/etc/rc.d/目录下。
	4. 
通过命令/etc/init.d/fa-rk3328-pwmfan start启动脚本。
	5. 
通过OpenWrt启动项页面可以看到fa-rk3328-pwmfan这个服务已经启动，并且风扇是停止的状态。（温度在关闭的范围）



使用一下命令让CPU产生负载：
dd if=/dev/zero of=/dev/null bs=1&
dd if=/dev/zero of=/dev/null bs=1&
dd if=/dev/zero of=/dev/null bs=1&
dd if=/dev/zero of=/dev/null bs=1&
CPU使用率增加到100%，CPU温度到60多度，风扇已经全速打开，并且温度能控制在60多度，通过ps -e | grep dd 查看使用dd命令的进程，通过kill命令逐个杀掉dd进程，CPU使用率下降，温度也下降，最终风扇会关闭。

参考链接：
	1. 
https://github.com/friendlyarm/friendlywrt/commit/e1fb88ff29bcf634c875b94a9026565c7780149f  friendlywrt官方固件added support for pwm fan提交
	2. 
https://github.com/friendlyarm/friendlywrt/tree/e1fb88ff29bcf634c875b94a9026565c7780149f/target/linux/rockchip-rk3328/base-files 所需脚本，注意有一个是rk3399的，rk3328不需要

**Comment by CWZ7605** [comment]
> 
> 
> 修改方法(所需文件请通过参考链接2下载)：
> 1.
> 通过OpenWrt TTYD终端上传friendlywrt/target/linux/rockchip-rk3328/base-files/usr/bin/start-rk3328-pwm-fan.sh到系统/usr/bin/目录下并通过chmod 777 start-rk3328-pwm-fan.sh修改脚本权限。
> 2.
> 通过OpenWrt TTYD终端上传friendlywrt/target/linux/rockchip-rk3328/base-files/etc/init.d/fa-rk3328-pwmfan到系统/etc/init.d/目录下，并通过chmod 777 fa-rk3328-pwmfan修改脚本权限。
> 3.
> 通过命令ln -s /etc/init.d/fa-rk3328-pwmfan /etc/rc.d/S96fa-rk3328-pwmfan创建一个启动脚本的软链接到/etc/rc.d/目录下。
> 4.
> 通过命令/etc/init.d/fa-rk3328-pwmfan start启动脚本。
> 5.
> 通过OpenWrt启动项页面可以看到fa-rk3328-pwmfan这个服务已经启动，并且风扇是停止的状态。（温度在关闭的范围）
> 
> 使用一下命令让CPU产生负载：
> dd if=/dev/zero of=/dev/null bs=1&
> dd if=/dev/zero of=/dev/null bs=1&
> dd if=/dev/zero of=/dev/null bs=1&
> dd if=/dev/zero of=/dev/null bs=1&
> CPU使用率增加到100%，CPU温度到60多度，风扇已经全速打开，并且温度能控制在60多度，通过ps -e | grep dd 查看使用dd命令的进程，通过kill命令逐个杀掉dd进程，CPU使用率下降，温度也下降，最终风扇会关闭。
> 
> 参考链接：
> 1.
> [friendlyarm/friendlywrt@e1fb88f](https://github.com/friendlyarm/friendlywrt/commit/e1fb88ff29bcf634c875b94a9026565c7780149f) friendlywrt官方固件added support for pwm fan提交
> 2.
> https://github.com/friendlyarm/friendlywrt/tree/e1fb88ff29bcf634c875b94a9026565c7780149f/target/linux/rockchip-rk3328/base-files 所需脚本，注意有一个是rk3399的，rk3328不需要

大佬真帅，给大佬点赞。溜了溜了
